

% buildResults = compiler.build.pythonPackage('makesqr.m', ...
%     'PackageName','MagicSquarePkg', ...
%     'SampleGenerationFiles','makesqrSample1.m', ...
%     'Verbose','on');


buildResults = compiler.build.pythonPackage('printCards.m', ...
    'PackageName','CardPrinter', ...
    'SampleGenerationFiles','testMakeCards.m', ...
    'Verbose','on');

%%

buildResults = compiler.build.pythonPackage('printCards1200.m', ...
    'PackageName','CardPrinter1200', ...
    'SampleGenerationFiles','test_print1200.m', ...
    'Verbose','on');